# Tokens are **examples only**.
# Use the REST Client extension for VSCode to test these endpoints.

@hostname = api.fennellabs.com
@port = 443

###
# @name Get Version
# @no-cookie-jar
GET /v1/get_version/
Host: {{hostname}}:{{port}}

###
# @name Health Check
# @no-cookie-jar
GET /v1/healthcheck/
Host: {{hostname}}:{{port}}

###
# @name Whiteflag Healthcheck
# @no-cookie-jar
GET /v1/whiteflag/healthcheck/
Host: {{hostname}}:{{port}}

###
# @name Fennel Healthcheck
# @no-cookie-jar
GET /v1/fennel/healthcheck/
Host: {{hostname}}:{{port}}

###
# @name Register
# @no-cookie-jar
POST /v1/auth/register/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
  "username": "testinguser",
  "email": "testinguser@test.com",
  "password": "testinguser"
}

###
# @name Login
# @no-cookie-jar
POST /v1/auth/login/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
  "username": "testinguser",
  "password": "testinguser"
}

###
# @name Logout
# @no-cookie-jar
POST /v1/auth/logout/
Host: {{hostname}}:{{port}}
Authorization: Token <token>

###
# @name Change Password
# @no-cookie-jar
POST /v1/auth/change_password/
Host: {{hostname}}:{{port}}
Authorization: Token <token>

{
    "old_password": "testinguser",
    "new_password": "testinguser2"
}

###
# @name Reset Password
# @no-cookie-jar
POST /v1/auth/reset_password/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "email": "testinguser@test.com"
}

###
# @name Reset Password Confirm
# @no-cookie-jar
POST /v1/auth/reset_password_confirm/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "token": "MjA:1jYXJkZW4uZmVubmVsbGFicw:1jYXJkZW4uZmVubmVsbGFicw",
    "new_password": "testinguser"
}


###
# @name Create API Group
# @no-cookie-jar
POST /v1/group/create/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "api_group_name": "test"
}


###
# @name Add User to API Group
# @no-cookie-jar
POST /v1/group/add_user/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "username": "testinguser",
    "api_group_name": "test"
}

###
# @name Remove User from API Group
# @no-cookie-jar
POST /v1/group/remove_user/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "username": "testinguser",
    "api_group_name": "test"
}

###
# @name Add Admin to API Group
# @no-cookie-jar
POST /v1/group/add_admin/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "username": "testinguser",
    "api_group_name": "test"
}

###
# @name Remove Admin from API Group
# @no-cookie-jar
POST /v1/group/remove_admin/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "username": "testinguser",
    "api_group_name": "test"
}

###
# @name Get Accounts Billable Count
# @no-cookie-jar
POST /v1/group/get_accounts_billable_count/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "api_group_name": "test"
}

###
# @name Get API Group Request Count
# @no-cookie-jar
POST /v1/group/get_api_group_request_count/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "api_group_name": "test"
}

###
# @name Whiteflag - Authenticate
# @no-cookie-jar
POST /v1/whiteflag/authenticate/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "verificationMethod": "1",
    "verificationData": "https://organisation.int/whiteflag"
}

###
# @name Whiteflag - Discontinue Authentication
# @no-cookie-jar
POST /v1/whiteflag/discontinue_authentication/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "referencedMessage": "0000000000000000000000000000000000000000000000000000000000000000",
    "verificationMethod": "1",
    "verificationData": "https://organisation.int/whiteflag"
}

###
# @name Whiteflag - Encode
# @no-cookie-jar
POST /v1/whiteflag/encode/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "prefix": "WF",
    "version": "1",
    "encryptionIndicator": "0",
    "duressIndicator": "1",
    "messageCode": "I",
    "referenceIndicator": "4",
    "referencedMessage": "3efb4e0cfa83122b242634254c1920a769d615dfcc4c670bb53eb6f12843c3ae",
    "subjectCode": "80",
    "datetime": "2013-08-31T04:29:15Z",
    "duration": "P00D00H00M",
    "objectType": "22",
    "objectLatitude": "+30.79658",
    "objectLongitude": "-037.82602",
    "objectSizeDim1": "8765",
    "objectSizeDim2": "3210",
    "objectOrientation": "042"
}

###
# @name Whiteflag - Decode
# @no-cookie-jar
POST /v1/whiteflag/decode/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "message": "5746313020a00000000000000000000000000000000000000000000000000000000000000000b43a3a38399d1797b7b933b0b734b9b0ba34b7b71734b73a17bbb434ba32b33630b380"
}

###
# @name Whiteflag Generate Shared Token
# @no-cookie-jar
GET /v1/whiteflag/generate_shared_token/
Host: {{hostname}}:{{port}}
Content-Type: application/json

###
# @name Whiteflag - Generate Public Token
# @no-cookie-jar
POST /v1/whiteflag/generate_public_token/
Host: {{hostname}}:{{port}}
Content-Type: application/json

{
    "sharedToken": "b35f89b6-df83-44c9-a59e-5647f248a058",
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Crypto - Generate Diffie-Hellman Keypair
# @no-cookie-jar
POST /v1/crypto/dh/generate_keypair/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token 9512982d2a0d9030b8be56c6f80a4b1d48b3d332766b759bde305573828a829e

###
# @name Crypto - Get My Keypair
# @no-cookie-jar
POST /v1/crypto/dh/get_my_keypair/
Content-Type: application/json
Authorization: Token <token>

###
# @name Crypto - Get Diffie-Hellman Shared Secret
# @no-cookie-jar
POST /v1/crypto/dh/get_shared_secret/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token ac1224a5a82d588ad1ea79d81c58cae3ac9c2f5acf116b30374fe9728602e73f

{
    "secret": "d8eb4daf0686892944e95b8b63e09f58ea4fdaeef0fe86e20d98e8b2a19c0072",
    "public": "0402ae7ca1142a2c64d979cf6cd039af9bc78241e893ef5bfec9f323e3b9ae4b"
}

###
# @name Crypto - DH Encrypt Whiteflag Message
# @no-cookie-jar
POST /v1/crypto/dh/whiteflag/encrypt_message/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token ac1224a5a82d588ad1ea79d81c58cae3ac9c2f5acf116b30374fe9728602e73f

{
    "message": "5746313020a00000000000000000000000000000000000000000000000000000000000000000b43a3a38399d1797b7b933b0b734b9b0ba34b7b71734b73a17bbb434ba32b33630b380",
    "shared_secret": "bc9fc6e2629eddd82ec1bdfae268288de8db724e12ebd3eb6f99d9a686cc457e"
}

###
# @name Crypto - DH Decrypt Whiteflag Message
# @no-cookie-jar
POST /v1/crypto/dh/whiteflag/decrypt_message/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token ac1224a5a82d588ad1ea79d81c58cae3ac9c2f5acf116b30374fe9728602e73f

{
    "message": "574631312af34c38e3af3ab687ac276965c11b369274da9ddf514bcc0eebf037a268f087f3bda708026b5f7a5b83e49072a2d32f83bc283c249601066c488a0a1e40bb4f27dcb409c14aa7c7b7f0f656c9bc184a8df6fbe7928a25d3e5b74a81ab16df93efcc30b1105c7ba56878afed34f318d337532a293b41c7b54d1af2c6b92414a79e68077655f7e3629bf93b2f43e553ebd518198c2cc1a782bcc3d37e1304f431c9997c803368f54ef2f2774f42543c32d",
    "shared_secret": "bc9fc6e2629eddd82ec1bdfae268288de8db724e12ebd3eb6f99d9a686cc457e"
}

###
# @name Crypto - Get DH Public Key by Username
# @no-cookie-jar
POST /v1/crypto/dh/get_public_key_by_username/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "username": "testinguser"
}

###
# @name Crypto - Get Public Key by Address
# @no-cookie-jar
POST /v1/crypto/dh/get_public_key_by_address/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "address": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt"
}

###
# @name Crypto - Check if Encrypted
# @no-cookie-jar
POST /v1/crypto/dh/whiteflag/is_this_encrypted/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: <token>

{
    "message": "5746313020a00000000000000000000000000000000000000000000000000000000000000000b43a3a38399d1797b7b933b0b734b9b0ba34b7b71734b73a17bbb434ba32b33630b380",
}

###
# @name Fennel - Create Account
# @no-cookie-jar
POST /v1/fennel/create_account/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Fennel - Download Account As JSON
# @no-cookie-jar
POST /v1/fennel/download_account_as_json/
Host: {{hostname}}:{{port}}
Authorization: Token <token>

###
# @name Fennel - Create Self Custodial Account
# @no-cookie-jar
POST /v1/fennel/create_self_custodial_account/
Host: {{hostname}}:{{port}}
Authorization: Token c1fdf33d948a726102a447de1d9bcd09970337308263d6bf2fe6b26281d8bab2

{
    "api_key": "<api_key>",
    "api_secret": "<api_secret>"
}

###
# @name Fennel - Reconstruct Self Custodial Account
# @no-cookie-jar
POST /v1/fennel/reconstruct_self_custodial_account/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token c1fdf33d948a726102a447de1d9bcd09970337308263d6bf2fe6b26281d8bab2

{
    "user_shard": "<user_share>",
    "api_key": "<api_key>",
    "api_secret": "<api_secret>" 
}

###
# @name Fennel - Get Self Custodial Account Address
# @no-cookie-jar
POST /v1/fennel/get_self_custodial_account_address/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "mnemonic": "<mnemonic>"
}

###
# @name Fennel - Download Self Custodial Account As JSON
# @no-cookie-jar
POST /v1/fennel/download_self_custodial_account_as_json/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token c1fdf33d948a726102a447de1d9bcd09970337308263d6bf2fe6b26281d8bab2

{
    "user_shard": "<user_share>",
    "api_key": "<api_key>",
    "api_secret": "<api_secret>"
}

###
# @name Fennel - Get Account Balance
# @no-cookie-jar
POST /v1/fennel/get_account_balance/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Fennel - Get Address
# @no-cookie-jar
POST /v1/fennel/get_address/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Get Fee For Transfer Token
# @no-cookie-jar
POST /v1/fennel/get_fee_for_transfer_token/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "to": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt",
    "amount": 100000
}

###
# @name Get Fee For Transfer Token
# @no-cookie-jar
POST /v1/fennel/transfer_token/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "to": "5CwBjJ48HW7c36dT7pAf9TkGQjj88jxw624xHaL6wtXJTWCt",
    "amount": 100000
}

###
# @name Fennel - Get Fee for New Signal
# @no-cookie-jar
POST /v1/fennel/get_fee_for_new_signal/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "signal": "This is a test message"
}

###
# @name Fennel - Send New Signal
# @no-cookie-jar
POST /v1/fennel/send_new_signal/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "signal": "This is a test message"
}

###
# @name Fennel - Get Fee for Send Signal List
# @no-cookie-jar
POST /v1/fennel/get_fee_for_send_signal_list/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "signals": ["This is a test message"]
}

###
# @name Fennel - Send Signal List
# @no-cookie-jar
POST /v1/fennel/send_signal_list/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "signals": [{"signal": "This is a test message", "recipient_group": "test_group"}]
}

###
# @name Fennel - Get Fee for Sync Signal
# @description Get the fee for sending a given signal which previously failed to sync to Fennel Network.
# @no-cookie-jar
POST /v1/fennel/get_fee_for_sync_signal/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "id": 0
}

###
# @name Fennel - Sync Signal
# @description Send a previously failed signal to Fennel Network.
# @no-cookie-jar
POST /v1/fennel/sync_signal/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6
Content-Type: application/json

{
    "id": 0
}

###
# @name Fennel - Confirm Signal
# @description Confirm a signal has been seen by a user.
# @no-cookie-jar
POST /v1/fennel/confirm_signal/
Host: {{hostname}}:{{port}}
Authorization: Token <token>
Content-Type: application/json

{
    "id": 0
}

###
# @name Fennel - Get Signal by ID
# @no-cookie-jar
GET /v1/fennel/get_signal_by_id/0/
HOST: {{hostname}}:{{port}}
Authorization: Token <token>

###
# @name Fennel - Get Signals
# @no-cookie-jar
GET /v1/fennel/get_signals/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Fennel - Get Latest 5 Signals
# @no-cookie-jar
GET /v1/fennel/get_signals/5/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Fennel - Get Unsynced Signals
# @description Get all signals which failed to sync to Fennel Network.
# @no-cookie-jar
GET /v1/fennel/get_unsynced_signals/
Host: {{hostname}}:{{port}}
Authorization: Token f4e2d291b6f5aa79227c59d1dc8902ee7b5c66dd94db6c17628fda171e1b1fd6

###
# @name Fennel - Get Fee History
# @description Retrieves historical fees from the chain.
# @no-cookie-jar
GET /v1/fennel/get_fee_history/
Host: {{hostname}}:{{port}}
Authorization: Token <token>

###
# @name Fennel - Get Fee History with Count
# @description Retrieves historical fees from the chain for a certain number of transactions.
# @no-cookie-jar
GET /v1/fennel/get_fee_history/5/
Host: {{hostname}}:{{port}}
Authorization: Token <token>

###
# @name Whiteflag - Encode List
# @no-cookie-jar
POST /v1/whiteflag/encode_list/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>

{
    "signals": [
        {
            "prefix": "WF",
            "version": "1",
            "encryptionIndicator": "0",
            "duressIndicator": "1",
            "messageCode": "I",
            "referenceIndicator": "4",
            "referencedMessage": "3efb4e0cfa83122b242634254c1920a769d615dfcc4c670bb53eb6f12843c3ae",
            "subjectCode": "80",
            "datetime": "2013-08-31T04:29:15Z",
            "duration": "P00D00H00M",
            "objectType": "22",
            "objectLatitude": "+30.79658",
            "objectLongitude": "-037.82602",
            "objectSizeDim1": "8765",
            "objectSizeDim2": "3210",
            "objectOrientation": "042"
        }
    ]
}

###
# @name Whiteflag - Decode List
# @no-cookie-jar
POST /v1/whiteflag/decode_list/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token 8254a8d30b94abf2cbb170c8d67d4aa3e41f941b36a5edafe97a9a74f42acf6c

{
    "signals": [3]
}

###
# @name Whiteflag - Get Fee for Send Signal with Annotations
POST /v1/whiteflag/get_fee_for_send_signal_with_annotations/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>
{
    "signal_body": {
            "encryptionIndicator": "0",
            "duressIndicator": "0",
            "messageCode": "I",
            "referenceIndicator": "4",
            "referencedMessage": "0000000000000000000000000000000000000000000000000000000000000000",
            "subjectCode": "52",
            "dateTime": "2023-09-01T09:37:09Z",
            "duration": "P00D00H00M",
            "objectType": "22",
            "objectLatitude": "+39.09144",
            "objectLongitude": "-120.03830",
            "objectSizeDim1": "0000",
            "objectSizeDim2": "0000",
            "objectOrientation": "000",
    },
    "annotations": {"test": "test"},
}

###
# @name Whiteflag - Send Signal with Annotations
POST /v1/whiteflag/send_signal_with_annotations/
Host: {{hostname}}:{{port}}
Content-Type: application/json
Authorization: Token <token>
{
    "signal_body": {
            "encryptionIndicator": "0",
            "duressIndicator": "0",
            "messageCode": "I",
            "referenceIndicator": "4",
            "referencedMessage": "0000000000000000000000000000000000000000000000000000000000000000",
            "subjectCode": "52",
            "dateTime": "2023-09-01T09:37:09Z",
            "duration": "P00D00H00M",
            "objectType": "22",
            "objectLatitude": "+39.09144",
            "objectLongitude": "-120.03830",
            "objectSizeDim1": "0000",
            "objectSizeDim2": "0000",
            "objectOrientation": "000",
    },
    "annotations": {"test": "test"},
}