# Generated by Django 4.0.8 on 2023-06-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userkeys_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeys",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
