# Generated by Django 4.0.8 on 2023-07-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_signal_mempool_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("function", models.CharField(max_length=256)),
                ("payload_size", models.IntegerField(default=0)),
                ("fee", models.IntegerField(default=0)),
            ],
        ),
    ]
