# Generated by Django 4.1.10 on 2023-07-12 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_remove_signal_confirmed_timestamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="confirmationrecord",
            unique_together={("signal", "confirmer")},
        ),
    ]
