# Generated by Django 4.1.10 on 2023-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_confirmationrecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
