# Generated by Django 4.1.10 on 2023-07-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_signal_tx_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeys",
            name="private_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userkeys",
            name="public_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="userkeys",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
