# Generated by Django 4.1.10 on 2023-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_userkeys_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userkeys",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
