# Generated by Django 4.1.10 on 2023-07-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_userkeys_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="signal_text",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="signal",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="function",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="userkeys",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userkeys",
            name="mnemonic",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="userkeys",
            name="private_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="userkeys",
            name="public_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
