# Generated by Django 4.1.10 on 2023-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_trustrequest_trustconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkeys",
            name="blockchain_public_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
