# Generated by Django 4.1.10 on 2023-08-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_apigroup_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apigroup",
            name="email",
            field=models.EmailField(max_length=1024),
        ),
    ]
