# Generated by Django 4.1.10 on 2023-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_apigroup_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
