# Generated by Django 4.1.10 on 2023-09-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_userkeys_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="references",
            field=models.ManyToManyField(
                related_name="referenced_by", to="main.signal"
            ),
        ),
    ]
