# Generated by Django 4.1.10 on 2023-09-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_apigroupjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="apigroup",
            name="private_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="apigroup",
            name="public_diffie_hellman_key",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
