# Generated by Django 4.1.10 on 2023-09-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_apigroup_private_diffie_hellman_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apigroupjoinrequest",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
