# Generated by Django 4.1.10 on 2023-10-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_signal_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="signal_body",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
