# Generated by Django 4.1.13 on 2024-06-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_signal_signal_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
