# Generated by Django 4.1.13 on 2024-08-02 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0036_signal_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="message_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="signal",
            name="subject_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="apigroupjoinrequest",
            unique_together={("user", "api_group")},
        ),
    ]
