# Generated by Django 4.1.13 on 2025-10-18 (Manual creation for A(0) authentication)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0039_add_pseudo_message_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteflagAuthentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[("1", "URL Validation"), ("2", "Shared Token")],
                        help_text="1=URL validation (Method 1), 2=Shared token (Method 2)",
                        max_length=1,
                    ),
                ),
                (
                    "verification_data",
                    models.CharField(
                        help_text="URL for Method 1, or token for Method 2",
                        max_length=4096,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain transaction hash of A(0) message",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False if A(4) discontinuation sent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteflag_authentication",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiteflag Authentication",
                "verbose_name_plural": "Whiteflag Authentications",
            },
        ),
    ]
