# Generated by Django on 2025-10-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_update_whiteflag_authentication_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_address', models.CharField(help_text="User's blockchain address where tokens should be sent", max_length=256)),
                ('requested_amount', models.DecimalField(decimal_places=4, default=10.0, help_text='Amount of tokens requested (default: 10.0)', max_digits=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for token request', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the request was fulfilled/rejected', null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash of token transfer', max_length=256, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this request', null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, help_text='Admin who fulfilled/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_token_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting tokens', on_delete=django.db.models.deletion.CASCADE, related_name='token_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Request',
                'verbose_name_plural': 'Token Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenrequest',
            index=models.Index(fields=['status', '-requested_at'], name='main_tokenr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenrequest',
            index=models.Index(fields=['user', '-requested_at'], name='main_tokenr_user_idx'),
        ),
    ]
