# Generated by Django 4.1.13 on 2025-10-22 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0042_tokenrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_type', models.CharField(default='6', help_text='Confirmation type (6=Confirm per Whiteflag spec)', max_length=1)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash of A(6) message', max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Whiteflag Confirmation',
                'verbose_name_plural': 'Whiteflag Confirmations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='tokenrequest',
            new_name='main_tokenr_status_9fe257_idx',
            old_name='main_tokenr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenrequest',
            new_name='main_tokenr_user_id_ad4f2d_idx',
            old_name='main_tokenr_user_idx',
        ),
        migrations.AddField(
            model_name='whiteflagauthentication',
            name='ecdh_counterpart',
            field=models.CharField(blank=True, help_text='Username of ECDH counterpart for peer-to-peer authentication', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whiteflagauthentication',
            name='ecdh_counterpart_key',
            field=models.CharField(blank=True, help_text="Counterpart's public key used in ECDH derivation", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='confirmer',
            field=models.ForeignKey(help_text='User who sent the confirmation', on_delete=django.db.models.deletion.CASCADE, related_name='confirmations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='target_authentication',
            field=models.ForeignKey(help_text='The authentication being confirmed', on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='main.whiteflagauthentication'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='target_user',
            field=models.ForeignKey(help_text='User who received the confirmation', on_delete=django.db.models.deletion.CASCADE, related_name='confirmations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='confirmation',
            unique_together={('confirmer', 'target_authentication')},
        ),
    ]
