name: Python application

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: quxWeHk_L^F7%ZjR&rLVpTqD8|jzHzU?rlG(i8|Wp)aH^_}=?z
      DEBUG: True
      ENVIRONMENT: CI-CD
      TESTING: Github Actions
      FENNEL_CLI_IP: https://bitwise.fennellabs.com
      FENNEL_SUBSERVICE_IP: https://subservice.fennellabs.com

    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt install libmemcached-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 main --count --extend-ignore E1101,W0613,R0903,C0301,C0114,C0115,C0116,R0801,E203 --exclude ./main/migrations,./main/tests --max-complexity=10 --max-line-length=127 --statistics
          flake8 dashboard --count --extend-ignore E1101,W0613,R0903,C0301,C0114,C0115,C0116,R0801,E203 --exclude ./dashboard/migrations,./dashboard/tests --max-complexity=10 --max-line-length=127 --statistics
      - name: Collect Static Files
        run: |
          python manage.py collectstatic
      - name: Run Tests
        run: |
          mkdir profile
          python manage.py migrate
          python manage.py test
